apiVersion: apps/v1
kind: Deployment
metadata:
  name: myreactapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: myreactapp
        image: myreactapp:latest
        imagePullPolicy: Never  # Use local images
        ports:
        - containerPort: 80